#### Write a function so that the columns of the output matrix are powers of the input vector. 
#### The order of the powers is determined by the increasing boolean argument. Specifically, when  increasing is False, the i-th output column is the input vector raised element-wise to the power  of N - i - 1. 
##### HINT: Such a matrix with a geometric progression in each row is named for Alexandre Theophile Vandermonde. 


In [4]:
import numpy as np

In [5]:
def my_vander(array,is_increasing):
    print(np.vander(array, increasing=is_increasing))

In [6]:
input_array = np.array([1,2,3,4])
my_vander(input_array,True)

[[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


#### Write a function to find moving average in an array over a window:  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3. |

In [7]:
def my_moving_average(array, weight):
    return np.convolve(array, np.ones(weight), 'valid') / weight

In [8]:
input_array = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
my_moving_average(input_array,3)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])